export const NEXT_PUBLIC_URL = process.env.NEXT_PUBLIC_URL || 'http://localhost:3000';

export const MOCK_SKILLS = [
  'JavaScript',
  'React',
  'Node.js',
  'TypeScript',
  'Python',
  'Django',
  'PostgreSQL',
  'AWS',
  'UI/UX Design',
  'Figma',
  'Adobe XD',
  'Sketch',
  'Design Systems',
  'Spanish',
  'French',
  'Italian',
  'TESOL',
  'Personal Training',
  'Yoga',
  'Nutrition',
  'Meditation',
  'Cooking',
  'Pasta',
  'Guitar',
  'Music Theory',
  'Photography',
  'Composition',
  'Marketing',
  'Strategy',
  'Business',
  'Chess',
  'Data Structures',
  'Algorithms'
];

